# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Cal_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
  test: 
        name: Test
        runs-on: ubuntu-latest
        needs: build   # <-- ensures this runs after the build job succeeds
        
        steps: 
          - uses: actions/checkout@v4
          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: 8.0.x
                
          - name: Restore dependencies
            run: dotnet restore
            
          - name: Build (for testing)
            run: dotnet build --no-restore --configuration Release
          - name: run tests
            run: dotnet test --no-build --verbosity normal
